version: 2.1
commands:
  build_docker_target:
    parameters:
      target:
        type: string
      cache_version:
        type: string
        default: v1
    steps:
      - run:
          name: maybe load cache
          command: |
            set +o pipefail
            docker pull $REGISTRY_URL/keda:<< parameters.target >> --quiet || true
      - run:
          name: build << parameters.target >>
          command: docker build . --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$REGISTRY_URL/keda:<< parameters.target >> --target << parameters.target >> -t keda:<< parameters.target >> --progress=plain
      - run:
          name: export << parameters.target >>
          command: |
            set +o pipefail
            docker tag keda:<< parameters.target >> $REGISTRY_URL/keda:<< parameters.target >> 
            docker push $REGISTRY_URL/keda:<< parameters.target >> --quiet || true

jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: cimg/base:2022.06
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
      BIN_RESULTS: /tmp/bin
      GO_MOD_CACHE: /tmp/go/pkg/mod
      DOCKER_BUILDKIT: 1
      REGISTRY_URL: ghcr.io/or-shachar
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: docker login
          command: echo $GITHUB_TOKEN |  docker login ghcr.io -u USERNAME --password-stdin
      - run:
          name: prep dirs
          command: mkdir -p $TEST_RESULTS && mkdir /tmp/docker-caches
      - build_docker_target:
          target: base
      - build_docker_target:
          target: tester
      - run:
          name: export test results
          command: |
            docker build . --target test-results --progress=plain --output $TEST_RESULTS/
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

      - build_docker_target:
          target: bin

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context:
            - ghcr_private
